run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - misspell

linters-settings:
  govet:
    enable-all: false
    disable:
      - fieldalignment # Field alignment optimization is disabled to keep struct layouts logical and readable
  errcheck:
    check-type-assertions: false
    check-blank: false

issues:
  exclude-use-default: true
  max-issues-per-linter: 50
  max-same-issues: 10
