package adapter

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/VinnyVanGogh/staypoint/internal/config"
)

// shimMarker is written into every bridge script generated by `staypoint adapter install`
// and `staypoint hook install`. A binary carrying it forwards back into staypoint, so
// executing it from the adapter would recurse.
const shimMarker = "Auto-generated by Staypoint"

// Resolver locates provider CLI binaries without hardcoded user paths.
//
// Precedence per provider: environment override, config override, then every
// PATH entry (via exec.LookPath) followed by ExtraDirs. Candidates that are the
// running staypoint executable or a staypoint bridge shim are skipped.
type Resolver struct {
	// Overrides maps provider name ("claude", "gemini") to an explicit binary path.
	Overrides map[string]string
	// Getenv reads environment variables; defaults to os.Getenv.
	Getenv func(string) string
	// ExtraDirs are searched after PATH (e.g. ~/.local/bin, which service
	// launchers often leave off PATH).
	ExtraDirs []string
	// Self is the resolved path of the current executable, used for the recursion guard.
	Self string
}

// envOverrideKeys lists the environment variables that override each provider binary.
var envOverrideKeys = map[string]string{
	"claude": "STAYPOINT_CLAUDE_BIN",
	"gemini": "STAYPOINT_AGY_BIN",
}

// NewDefaultResolver builds a Resolver from the user's staypoint config and environment.
// Config load errors are ignored so a broken config never stops the adapter from
// falling back to PATH.
func NewDefaultResolver() *Resolver {
	r := &Resolver{Overrides: map[string]string{}, Getenv: os.Getenv}
	if cfg, err := config.LoadConfig(); err == nil && cfg != nil {
		r.Overrides["claude"] = cfg.ClaudeBin
		r.Overrides["gemini"] = cfg.AgyBin
	}
	if home, err := os.UserHomeDir(); err == nil {
		r.ExtraDirs = []string{filepath.Join(home, ".local", "bin")}
	}
	if self, err := os.Executable(); err == nil {
		r.Self = canonicalPath(self)
	}
	return r
}

// Resolve returns the absolute path of the CLI binary for the given adapter.
func (r *Resolver) Resolve(a ProviderAdapter) (string, error) {
	provider := a.Provider()
	getenv := r.Getenv
	if getenv == nil {
		getenv = os.Getenv
	}

	if key, ok := envOverrideKeys[provider]; ok {
		if p := strings.TrimSpace(getenv(key)); p != "" {
			return r.checkOverride(p, key)
		}
	}
	if p := strings.TrimSpace(r.Overrides[provider]); p != "" {
		return r.checkOverride(p, "config "+provider+" binary override")
	}

	dirs := filepath.SplitList(getenv("PATH"))
	dirs = append(dirs, r.ExtraDirs...)
	seen := map[string]bool{}
	for _, dir := range dirs {
		if dir == "" {
			continue
		}
		candidate, err := exec.LookPath(filepath.Join(dir, a.BinaryName()))
		if err != nil {
			continue
		}
		canon := canonicalPath(candidate)
		if seen[canon] {
			continue
		}
		seen[canon] = true
		if r.isSelfOrShim(canon) {
			continue
		}
		return candidate, nil
	}

	hint := ""
	if key, ok := envOverrideKeys[provider]; ok {
		hint = fmt.Sprintf("; install it or set %s", key)
	}
	return "", fmt.Errorf("%s CLI %q not found on PATH%s", provider, a.BinaryName(), hint)
}

func (r *Resolver) checkOverride(p, source string) (string, error) {
	resolved, err := exec.LookPath(p)
	if err != nil {
		return "", fmt.Errorf("%s %q is not an executable: %w", source, p, err)
	}
	if r.isSelfOrShim(canonicalPath(resolved)) {
		return "", fmt.Errorf("%s %q points back at staypoint (would recurse)", source, p)
	}
	return resolved, nil
}

func (r *Resolver) isSelfOrShim(canon string) bool {
	if r.Self != "" && canon == r.Self {
		return true
	}
	return isStaypointShim(canon)
}

// isStaypointShim reports whether path is a small script generated by staypoint.
func isStaypointShim(path string) bool {
	f, err := os.Open(path)
	if err != nil {
		return false
	}
	defer f.Close()
	head := make([]byte, 512)
	n, _ := f.Read(head)
	head = head[:n]
	return bytes.HasPrefix(head, []byte("#!")) && bytes.Contains(head, []byte(shimMarker))
}

func canonicalPath(p string) string {
	if abs, err := filepath.Abs(p); err == nil {
		p = abs
	}
	if real, err := filepath.EvalSymlinks(p); err == nil {
		p = real
	}
	return p
}
