package main

import (
	"context"
	"fmt"
	"os"

	"github.com/spf13/cobra"
	"github.com/VinnyVanGogh/staypoint/internal/adapter"
	"github.com/VinnyVanGogh/staypoint/internal/router"
)

var adapterCmd = &cobra.Command{
	Use:                "adapter [provider] [args...]",
	Short:              "Agent adapter with failover, quota-gating, and anti-stall streaming",
	DisableFlagParsing: true,
	Run: func(cmd *cobra.Command, args []string) {
		if len(args) == 0 || args[0] == "-h" || args[0] == "--help" {
			_ = cmd.Help()
			return
		}

		if args[0] == "install" {
			runAdapterInstall()
			return
		}

		provider := args[0]
		rawArgs := args[1:]

		pacerState, _ := router.LoadPacerState()
		cwd, _ := os.Getwd()

		err := adapter.RunAdapter(context.Background(), cwd, pacerState, provider, rawArgs, os.Stdout, os.Stderr)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Adapter error: %v\n", err)
			os.Exit(1)
		}
	},
}

func init() {
	rootCmd.AddCommand(adapterCmd)
}

func runAdapterInstall() {
	home, err := os.UserHomeDir()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
	binDir := home + "/.local/bin"
	_ = os.MkdirAll(binDir, 0755)

	geminiPath := binDir + "/gemini-paperclip-bridge"
	claudePath := binDir + "/claude-paperclip-bridge"

	scriptTemplate := `#!/usr/bin/env bash
# Auto-generated by Staypoint
exec staypoint adapter %s "$@"
`
	err = os.WriteFile(geminiPath, []byte(fmt.Sprintf(scriptTemplate, "gemini")), 0755)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to write %s: %v\n", geminiPath, err)
	} else {
		fmt.Printf("Installed %s\n", geminiPath)
	}

	err = os.WriteFile(claudePath, []byte(fmt.Sprintf(scriptTemplate, "claude")), 0755)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to write %s: %v\n", claudePath, err)
	} else {
		fmt.Printf("Installed %s\n", claudePath)
	}
}

var adapterInstallCmd = &cobra.Command{
	Use:   "install",
	Short: "Install Staypoint adapter bridges to ~/.local/bin",
	Run: func(cmd *cobra.Command, args []string) {
		runAdapterInstall()
	},
}

func init() {
	adapterCmd.AddCommand(adapterInstallCmd)
}
